const InquiryActionTypes = {
    SET_INQUIRIES: "SET_INQUIRIES",
    ADD_NEW_INQUIRIES: "ADD_NEW_INQUIRIES",
    MARK_INQUIRIES_AS_READ: "MARK_INQUIRIES_AS_READ",
    MARK_INQUIRIES_AS_UNREAD: "MARK_INQUIRIES_AS_UNREAD",
    MARK_INQUIRY_AS_STARRED: "MARK_INQUIRY_AS_STARRED",
    MARK_INQUIRY_AS_UNSTARRED: "MARK_INQUIRY_AS_UNSTARRED",
    DELETE_INQUIRIES: "DELETE_INQUIRIES",
};

export default InquiryActionTypes;
